# docker-image.yml

name: Publish Docker Images

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    build-and-push-awg-docker-bot:
        name: awg-docker-bot to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub using token
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push awg-docker-bot image
              uses: docker/build-push-action@v5
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  tags: the80hz/awg-docker-bot:${{ github.sha }},the80hz/awg-docker-bot:latest